### ISSUE TITLE
Rel. 1.0.9.7 : TO SDR SYNC

### ISSUE THREAD

**Issue by I2BRT** [martinbradford/101Cats#11]
Strange issue with 101Cats and Sdruno.

Left click or Right click on "TO SDR" button seems to produce no effect.
Left click or Right click on "FROM SDR" button it works as supposed to be.

Cat cable is setup via com0com (31<->32). 31 is setup in 101cats, 32 in Sdruno.
As a test, I tried to configure Flrig on port 31 (kenwood protocol) and I was able to read/send cat frequencies to sdruno on port 32.
Best 73 de Rick

**Comment by martinbradford** [comment]
Have you checked the "App" setting in config.xml? That specifies which application - SDR Uno or SDR Console - is being used \:

	
	<SDRPort enable="false">
	  <PortName>COM44</PortName>
	  <PortSpeed>38400</PortSpeed>
		<App>SDRUNO</App>
	</SDRPort>

I think the default is probably SDRCONSOLE. There is currently no option to set this through the configuration dialogue box - it is necessary to hand-edit the xml file. See the Wiki pages for instructions if you've not done it before...

**Comment by I2BRT** [comment]
You're right. User error.
I did'nt notice that there was an <App> record in the XML file and that was set up for SDRCONSOLE.
Now:
<SDRPort enable="true">
      <PortName>COM31</PortName>
      <PortSpeed>38400</PortSpeed>
	      <App>SDRUNO</App>
    </SDRPort>
IT WORKS.

Sorry... you can close this issue.
Best 73 de Rick.

**Comment by martinbradford** [comment]
Not a problem, Rick - support for SDR Uno is a recent addition and not well documented yet. Until last week, I always ran SDR Console and the 101Cats code was written for that. I'm now switching to SDRUno for its diversity reception capabilities and had to add the extra option to the configuration file. I will add it to the configuration dialogue soon...
