### ISSUE TITLE
BUG: Band selection app <-> radio. 

### ISSUE THREAD

**Issue by kvenl** [martinbradford/101Cats#14]
When tuning the radio to 27 MHz CB band, the app reflects 24.5 band.
When tuning the radio to a GEN frequency of 6130 kHz, the app reflects 5 Band
So it's reflecting the lower HAM band.

Version 1.0.9.7

Kees
ON9KVE

**Comment by martinbradford** [comment]
Are you referring to the band selection combo-box, or the textual description below the frequency display?

**Comment by kvenl** [comment]
The combobox Martin

**Comment by martinbradford** [comment]
Ok  - when I get my PC booted up tomorrow, I'll take a look to see how that is derived. Been a long time since I implemented that and I've forgotten.

**Comment by martinbradford** [comment]
Unfortunately, the Band Select CAT command is input only - the radio does not report the band. 101Cats monitors the tuned frequency and infers the band. The frequencies that you quote above are not in the amateur bands and my inferred value is the next band down - what do you think it should be?

**Comment by kvenl** [comment]
Can't you add a codeswitch that changes "y" if found aband, and then if switch = n it's GEN ? 
Just asking ...

**Comment by martinbradford** [comment]
It really is overcomplicating a working bit of code for the sake of keeping a picky code tester happy! :-)

The official way of reporting the selected band is the band name text field under the frequency dissplay - that is user configurable! Sorry, but I'm closing this one!
