### ISSUE TITLE
Antenna 3 Function

### ISSUE THREAD

**Issue by I2RNJ** [martinbradford/101Cats#6]
Posted on Groups.io discussion too.

Hi Martin, nice application, really.
I am testing version 1.0.9.0 without any issue, but maybe something is missing, unless it could be my misunderstanding.
Under "Antenna 3 Function" I cannot see TRX, while on FTDX101 menu, the function is selectable.
Possibly, could be admissible to make an alert opening the selection tab, to preserve enabling the TRX function while using ANT 3 socket for different use, such as SDR receiver for example.

73
Roberto
I2RNJ

**Comment by martinbradford** [comment]
Fixed in V1.0.9.1 uploaded 06/05/2024. See explanation in Wiki for more details. Can you test and close please, Roberto?
