### ISSUE TITLE
Frequency setting

### ISSUE THREAD

**Issue by I2RNJ** [martinbradford/101Cats#8]
Martin, the frequency panel doesn't work properly.
Clicking the mouse on frequency display, opens the panel, but entering the new value, it seems having any effect in changing on the FTDX101.
Could you check?
73 Roberto I2RNJ

**Comment by I2RNJ** [comment]
Sorry Martin, I discovered due to an other software opened. It works good

**Comment by martinbradford** [comment]
I still think there is a bug there - currently testing

**Comment by martinbradford** [comment]
You are quite right - now fixed - a new version will be published in a few minutes

**Comment by martinbradford** [comment]
1.0.9.2 uploaded  - please close issue when you are able to test...

**Comment by martinbradford** [comment]
There is always a selected digit in the frequency display - that is the digit that will be increased or decreased by rotating the mouse wheel. You can choose which digit to vary by clicking on it. If you depress either the Control key, the Shift key or both Control and Shift at the same time, you will temporarily move the selected digit up for faster tuning...

You can change the colour theme by editing the config.xml file. Unfortunately, this is not an option that can be configured via the dialogue box - you do have to edit the file **and make sure you take a backup of it first**. The entry is close to the top of the file and reads something like this 

	<Theme>
		<BaseTheme>Dark.Brown</BaseTheme>
	</Theme>

permissible values are

			Application Theme.

			101Cats is built using the MahApps UI framework which supports Theming. Currently, only MahApps stock
			themes are supported. A future version may support theme customization. The stock themes are :
			
			"Red", "Green", "Blue", "Purple", "Orange", "Lime", "Emerald", "Teal", "Cyan", "Cobalt", "Indigo", "Violet", 
			"Pink", "Magenta", "Crimson", "Amber", "Yellow", "Brown", "Olive", "Steel", "Mauve", "Taupe", "Sienna"

			and these base themes:

				"Light", "Dark"

My configuration is 

  <Theme>
    <BaseTheme>Dark.Cyan</BaseTheme>
  </Theme>

which I find quite readable.

You can set the initial value of APO and the timeout through the configuration dialogue box (use the "Configure" link in the title bar...

**Comment by martinbradford** [comment]
Are you editing the correct **config.xml**? One is installed in the **Program Files** sub-directory, but that is just the initial version. When you run 101Cats for the first time, it is copied into your AppData directory and that is the live copy that is referenced by the application. See the Wiki for a more detailed explanation

**Comment by I2RNJ** [comment]
Yes, true. Thanks Martin
